name = "kangae"
description = "a lightweight microblog theme for zola"
license = "NCSA"
homepage = "https://github.com/ayushnix/kangae"
demo = "https://kangae.ayushnix.com/"
min_version = "0.15.0"

[author]
name = "Ayush Agarwal"
homepage = "https://microblog.ayushnix.com"
